### ISSUE TITLE
Seed file generator goes over 100%

### ISSUE THREAD

**Issue by rbychn** [SmithUnity/prosanity#1]

**Comment by rbychn** [comment]
Saw CPU4 at 103% for \cmd\seedFileGenerator\main.go and had to force stop

**Comment by CactusByte** [comment]
Same issue

**Comment by fala13** [comment]
https://en.wikipedia.org/wiki/Per_mille

**Comment by Mullerchens** [comment]
Did you guys figure it out why it keeps going?

**Comment by cylzxje** [comment]
how do i actually use this lol
